### ISSUE TITLE
Typescript types definitions

### ISSUE THREAD

**Issue by levibostian** [honeybadger-io/honeybadger-node#52]
Hey there. 

I am using honeybadger-node in my Typescript nodejs application. After installing honeybadger via npm, VSCode complains about not finding type declarations for the honeybadger module. 

My question: Is there a step I am missing to get type declarations installed for my application? Or, do they not exist and they need to be added to this repo? 

I noticed that honeybadger-js has types included. Can I use those declarations or will this repo require having different types defined? 

Anyway I can help?

**Comment by joshuap** [comment]
@levibostian sorry, missed this issue somehow.

We don't have type definitions for honeybadger-node yet. A PR would be appreciated! I don't think the honeybadger-js definitions will work directly because these are different libraries, although you may be able to use them as a starting point.

Eventually, I'd love to combine the two libraries (using a mono-repo or something like that), and then they could share definitions. That's a bit down the road, though.

**Comment by levibostian** [comment]
Cool! `@types/honeybadger` [is live](https://www.npmjs.com/package/@types/honeybadger)! 

Up to you, but if you want to add a note to the readme or docs about this for typescript devs it may be helpful.
