### ISSUE TITLE
Releases > v1.0.0 hang when sending on AWS Lambda

### ISSUE THREAD

**Issue by WilHall** [honeybadger-io/honeybadger-node#9]
When using Honeybadger on AWS Lambda with the `nodejs4.3` runtime, The `v1.0.0` release of `honeybadger-node` works as expected. However, in testing with `v1.1.0` and `v1.1.1` without any code changes, the function times out.

The case I'm testing with is very simplistic. At the beginning of the function:
```
var Honeybadger = require('honeybadger');
Honeybadger.configure({
  apiKey: process.env.HONEYBADGER_API_KEY
});
```

And then within my handler function:
```
Honeybadger.notify("Test message");
```
*I am not using `Honeybadger.lambdaHandler` to build my handler.*

With `v1.0.0`, my handler executes and Honeybadger receives `"Test message"`.
With versions `> v1.0.0`, my handler executes, but afterwards the function times out instead of exiting successfully. I believe that Honeybadger is failing to connect/send properly in these cases.

**Comment by joshuap** [comment]
@WilHall Ah, thanks. I think the issue was introduced here:

https://github.com/honeybadger-io/honeybadger-node/commit/2b319baecd3fc548e35f32d82b8ee4ee55762f95#diff-7308343c48307deeaca237900425d640R24

The nodejs4.3 runtime on Lambda now waits for the event loop to clear (which is great for errors, actually, and may let me simplify or remove the `lambdaHandler` in favor of `Honeybadger.notify` and `Honeybadger.wrap`). I think the issue is that the new metrics collector uses a `setTimeout` to report metrics every so often, and Lambda is probably timing out while it waits for the event loop to empty. Does that sound right?

I probably need to ditch the use of `setTimeout` for the collector and find another way to flush metrics at an interval as they are collected.

**Comment by WilHall** [comment]
> I think the issue is that the new metrics collector uses a setTimeout to report metrics every so often, and Lambda is probably timing out while it waits for the event loop to empty.

That sounds correct.

See my latest comment on #10 - if I'm understanding correctly, you may be able to keep `Honeybadger.lambdaHandler` and wrap the lambda handler [callback parameter](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback), and then instead of sending metrics on an interval, send them when the wrapper that Honeybadger creates for the `callback` fires, before calling the original callback. This would mean that Honeybadger would send after the handler function had finished executing.

The problem is that if `callback` *doesn't get called* - this could either be by mistake (e.g. the user forgets to call it) or because we are pre-`nodejs4.3` - then Honeybadger would never send. Perhaps this could fallback to a time interval send somehow?
